USE gerenciamento_salao_beleza;

CREATE TABLE PRODUTOS (
	ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO TEXT,
    PREÇO_COMPRA FLOAT NOT NULL, 
	PREÇO_VENDA FLOAT NOT NULL,
	DATA_COMPRA DATETIME NOT NULL,
	DATA_VENDA DATETIME NOT NULL
);