USE gerenciamento_salao_beleza;

CREATE TABLE COLABORADORES (
	ID_COLABORADOR INT AUTO_INCREMENT PRIMARY KEY,
	NOME_COLABORADOR TEXT NOT NULL,
	ENDEREÇO TEXT NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL
);